from datetime import datetime
from typing import Any

from sqlalchemy import JSON, Boolean, CheckConstraint, ForeignKey, Index, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.types import UTCDateTime, new_id, utcnow
from app.models.base import Base, TimestampMixin

FORM_STATUSES = ("draft", "published")


class Form(TimestampMixin, Base):
    """The editable draft of a form. Respondents never see this directly;
    they see the immutable FormVersion pointed to by `published_version_id`."""

    __tablename__ = "forms"
    __table_args__ = (CheckConstraint("status IN ('draft', 'published')", name="ck_forms_status"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    workspace_id: Mapped[str] = mapped_column(ForeignKey("workspaces.id", ondelete="CASCADE"), index=True)
    title: Mapped[str] = mapped_column(String(255))
    status: Mapped[str] = mapped_column(String(16), default="draft")
    # Assigned on first publish and kept afterwards, so the share link never changes.
    slug: Mapped[str | None] = mapped_column(String(32), unique=True)
    # Bumped on every draft change; used for optimistic concurrency in autosave.
    draft_revision: Mapped[int] = mapped_column(Integer, default=1)
    published_version_id: Mapped[str | None] = mapped_column(
        ForeignKey("form_versions.id", ondelete="SET NULL", use_alter=True, name="fk_forms_published_version_id")
    )
    # Set on the seeded demo forms so they can be restored if a visitor deletes them.
    demo_key: Mapped[str | None] = mapped_column(String(40), unique=True)
    # Theme + thank-you screen. Validated by schemas.definition.FormSettings.
    settings_json: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)

    questions: Mapped[list["Question"]] = relationship(
        back_populates="form", order_by="Question.position", cascade="all, delete-orphan"
    )
    versions: Mapped[list["FormVersion"]] = relationship(
        foreign_keys="FormVersion.form_id", back_populates="form", cascade="all, delete-orphan", passive_deletes=True
    )
    published_version: Mapped["FormVersion | None"] = relationship(
        foreign_keys=[published_version_id], post_update=True
    )


class Question(TimestampMixin, Base):
    __tablename__ = "questions"
    __table_args__ = (Index("ix_questions_form_position", "form_id", "position"),)

    # Generated by the client so the builder can reference new questions before saving.
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    form_id: Mapped[str] = mapped_column(ForeignKey("forms.id", ondelete="CASCADE"))
    position: Mapped[int] = mapped_column(Integer)
    type: Mapped[str] = mapped_column(String(32))
    title: Mapped[str] = mapped_column(Text, default="")
    description: Mapped[str] = mapped_column(Text, default="")
    required: Mapped[bool] = mapped_column(Boolean, default=False)
    # Type-specific config (placeholder, min/max, rating steps...). See validators/question_types.py.
    settings_json: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    # Logic jumps: [{"op", "value", "goto"}], see schemas.definition.LogicRule.
    logic_json: Mapped[list[dict[str, Any]]] = mapped_column(JSON, default=list, server_default="[]")

    form: Mapped[Form] = relationship(back_populates="questions")
    options: Mapped[list["QuestionOption"]] = relationship(
        back_populates="question", order_by="QuestionOption.position", cascade="all, delete-orphan"
    )


class QuestionOption(Base):
    """An answer choice for multiple_choice / dropdown questions."""

    __tablename__ = "question_options"
    __table_args__ = (Index("ix_question_options_question_position", "question_id", "position"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    question_id: Mapped[str] = mapped_column(ForeignKey("questions.id", ondelete="CASCADE"))
    position: Mapped[int] = mapped_column(Integer)
    label: Mapped[str] = mapped_column(String(500), default="")

    question: Mapped[Question] = relationship(back_populates="options")


class FormVersion(Base):
    """Immutable snapshot of a form, created on every publish. Submissions point here,
    so old responses stay interpretable after the draft is edited."""

    __tablename__ = "form_versions"
    __table_args__ = (UniqueConstraint("form_id", "version_number", name="uq_form_versions_form_number"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    form_id: Mapped[str] = mapped_column(ForeignKey("forms.id", ondelete="CASCADE"), index=True)
    version_number: Mapped[int] = mapped_column(Integer)
    # The draft_revision this snapshot was taken from (detects unpublished changes).
    source_revision: Mapped[int] = mapped_column(Integer)
    definition_json: Mapped[dict[str, Any]] = mapped_column(JSON)
    published_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)

    form: Mapped[Form] = relationship(foreign_keys=[form_id], back_populates="versions")
