from datetime import datetime
from typing import Any

from sqlalchemy import JSON, ForeignKey, Index, Integer, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.types import UTCDateTime, new_id, utcnow
from app.models.base import Base


class Submission(Base):
    __tablename__ = "submissions"
    __table_args__ = (Index("ix_submissions_form_submitted", "form_id", "submitted_at"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    form_id: Mapped[str] = mapped_column(ForeignKey("forms.id", ondelete="CASCADE"))
    form_version_id: Mapped[str] = mapped_column(ForeignKey("form_versions.id", ondelete="CASCADE"), index=True)
    # Generated by the browser once per fill; a retried/double-clicked submit reuses it.
    client_submission_id: Mapped[str] = mapped_column(String(64), unique=True)
    submitted_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)

    answers: Mapped[list["Answer"]] = relationship(
        back_populates="submission", cascade="all, delete-orphan", passive_deletes=True
    )


class Answer(Base):
    __tablename__ = "answers"
    __table_args__ = (UniqueConstraint("submission_id", "question_id", name="uq_answers_submission_question"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    submission_id: Mapped[str] = mapped_column(ForeignKey("submissions.id", ondelete="CASCADE"))
    # Deliberately NOT a foreign key to questions: the question may be deleted from the
    # draft later, but it still exists in the FormVersion snapshot this answer belongs to.
    question_id: Mapped[str] = mapped_column(String(36), index=True)
    # str for text/email, number, bool for yes/no, int for rating,
    # option id (dropdown) or list of option ids (multiple choice).
    value_json: Mapped[Any] = mapped_column(JSON)

    submission: Mapped[Submission] = relationship(back_populates="answers")


class ResponseSession(Base):
    """One respondent visit to a published form. Powers views / starts / completion rate."""

    __tablename__ = "response_sessions"
    __table_args__ = (Index("ix_response_sessions_form", "form_id"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    form_id: Mapped[str] = mapped_column(ForeignKey("forms.id", ondelete="CASCADE"))
    client_session_id: Mapped[str] = mapped_column(String(64), unique=True)
    viewed_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    started_at: Mapped[datetime | None] = mapped_column(UTCDateTime)
    submitted_at: Mapped[datetime | None] = mapped_column(UTCDateTime)


class FileUpload(Base):
    """A file a respondent uploaded for a file_upload question. Uploaded before the
    submission exists (so big files don't block submit), then attached to it."""

    __tablename__ = "file_uploads"
    __table_args__ = (Index("ix_file_uploads_form", "form_id"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    form_id: Mapped[str] = mapped_column(ForeignKey("forms.id", ondelete="CASCADE"))
    question_id: Mapped[str] = mapped_column(String(36))
    # NULL until a submission claims it; SET NULL keeps the row if a submission is removed.
    submission_id: Mapped[str | None] = mapped_column(ForeignKey("submissions.id", ondelete="SET NULL"), index=True)
    filename: Mapped[str] = mapped_column(String(255))
    content_type: Mapped[str] = mapped_column(String(127))
    size_bytes: Mapped[int] = mapped_column(Integer)
    # Name of the file inside settings.upload_dir (never the user-supplied name).
    storage_key: Mapped[str] = mapped_column(String(64), unique=True)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
